genres = ['drama', 'romance', 'sci-fi', 'fantasy', 'horror', 'comedy', 'mystery']

anime_data =   [['drama', 'Shingeki no Kyojin (Attack on Titan)'],
                ['drama', 'Fullmetal Alchemist: Brotherhood'],
                ['drama', 'Tokyo Ghoul'],
                ['drama', 'Kimi no Na wa (Your Name)'],
                ['drama', 'Steins;Gate'],
                ['drama', 'Re:Zero kara Hajimeru Isekai Seikatsu'],
                ['drama', 'Shigatsu wa Kimi no Uso (Your Lie in April)'],
                ['drama', 'Koe no Katachi (A Silent Voice)'],
                ['drama', 'One Piece'],
                ['drama', 'Haikyuu!!'],
                ['romance', 'Sword Art Online'],
                ['romance', 'Kimi no Na wa (Your Name)'],
                ['romance', 'Toradora'],
                ['romance', 'Shigatsu wa Kimi no Uso (Your Lie in April)'],
                ['romance', 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai'],
                ['romance', 'Bakemonogatari'],
                ['romance', 'Howl no Ugoku Shiro (Howl\'s Moving Castle)'],
                ['sci-fi', 'One Punch Man'],
                ['sci-fi', 'Steins;Gate'],
                ['sci-fi', 'Yakusoku no Neverland (The Promised Neverland)'],
                ['sci-fi', 'Cowboy Bebop'],
                ['sci-fi', 'Neon Genesis Evangelion'],
                ['sci-fi', 'Dr. Stone'],
                ['sci-fi', 'Edens:Zero'],
                ['fantasy', 'Shingeki no Kyojin (Attack on Titan)'],
                ['fantasy', 'Fullmetal Alchemist: Brotherhood'],
                ['fantasy', 'Sword Art Online'],
                ['fantasy', 'Hunter x Hunter'],
                ['fantasy', 'No Game No Life'],
                ['fantasy', 'Akame ga Kill!'],
                ['fantasy', 'One Piece'],
                ['fantasy', 'Fairy Tail'],
                ['fantasy', 'Violet Evergarden'],
                ['fantasy', 'Black Clover'],
                ['fantasy', 'Dragon Ball Z'],
                ['fantasy', 'Nanatsu no Taizai (Seven Deadly Sins)'],
                ['horror', 'Tokyo Ghoul'],
                ['horror', 'Yakusoku no Neverland (The Promised Neverland)'],
                ['horror', 'Another'],
                ['horror', 'Elfen Lied'],
                ['comedy', 'Fullmetal Alchemist: Brotherhood'],
                ['comedy', 'One Punch Man'],
                ['comedy', 'Boku no Hero Academia'],
                ['comedy', 'Naruto'],
                ['comedy', 'No Game No Life'],
                ['comedy', 'Toradora!'],
                ['comedy', 'One Piece'],
                ['comedy', 'Haikyuu!!'],
                ['mystery', 'Death Note'],
                ['mystery', 'Shingeki no Kyojin (Attack on Titan)'],
                ['mystery', 'Tokyo Ghoul'],
                ['mystery', 'Yakusoku no Neverland (The Promised Neverland)'],
                ['mystery', 'Bakemonogatari']]